async page => {
  const check = (condition, message) => { if (!condition) throw new Error(message) }
  await page.goto('http://127.0.0.1:8764/output/showcase-site/index.html#menu')
  await page.reload()
  await page.waitForFunction(() => document.querySelectorAll('.dish-name').length === 4)
  await page.getByText('肉肉', { exact: true }).click()
  check(await page.locator('.dish-name').count() === 1, 'category filters one dish')
  check(await page.locator('.dish-name').textContent() === '香煎三文鱼', 'category mapping')
  await page.getByText('全部', { exact: true }).click()
  await page.getByPlaceholder('搜索菜名或标签').fill('意面')
  check(await page.locator('.dish-name').count() === 1, 'search filters one dish')
  await page.getByRole('button', { name: '+', exact: true }).click()
  check(await page.locator('.selection-summary').innerText() === '已选 1 道 ⌃', 'add updates count')
  await page.getByRole('button', { name: '−', exact: true }).click()
  check(await page.locator('.selection-summary').count() === 0, 'remove resets selection')
  await page.getByRole('button', { name: '+', exact: true }).click()
  await page.getByPlaceholder('搜索菜名或标签').fill('不存在的菜')
  check(await page.getByText('没有找到这道菜', { exact: true }).count() === 1, 'search empty state')
  await page.getByPlaceholder('搜索菜名或标签').fill('')
  await page.locator('.dish-card').filter({ hasText: '香煎三文鱼' }).getByRole('button').click()
  await page.getByRole('button', { name: '选好了，加入饭单', exact: true }).click()
  await page.waitForFunction(() => location.hash === '#meal')
  await page.waitForFunction(() => document.querySelectorAll('.meal-item').length === 2)
  check(await page.locator('.meal-item').count() === 2, 'local meal has selected two dishes')
  check(await page.locator('.meal-heading-title').textContent() === '演示饭单', 'local meal label')
  await page.getByRole('button', { name: '确认菜单', exact: true }).click()
  check(await page.locator('#toast').isVisible(), 'unsupported save gives truthful feedback')
  await page.getByRole('link', { name: '吃饭详情', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.dish-memory-row').length === 3)
  check(await page.locator('.dish-memory-row').count() === 3, 'historical demo remains three dishes')
  await page.getByRole('link', { name: '完整 Menu', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('#menuCanvas')?.width === 1800 && document.body.dataset.ready === 'true')
  check(await page.locator('canvas').count() === 1, 'full menu canvas displayed')
  await page.goto('http://127.0.0.1:8764/output/showcase-site/index.html#records')
  await page.reload()
  await page.waitForFunction(() => document.querySelectorAll('.timeline-item').length === 3)
  check(await page.locator('.timeline-item').count() === 3, 'records page')
  await page.getByRole('link', { name: '我们', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.member').length === 2)
  check(await page.locator('.member').count() === 2, 'fictional two-person space')
  await page.getByRole('link', { name: '心愿', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.wish-item').length === 2)
  check(await page.locator('.wish-item').count() === 2, 'wishes page')
  await page.getByRole('link', { name: '菜单', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.dish-name').length === 4)
  check(await page.locator('.selection-summary').count() === 0, 'refresh resets memory')
  check(await page.locator('.dish-name').count() === 4, 'default menu restored')
  console.log('Verified: category, search, empty state, add/remove, local meal, read-only warning, Menu, records, space, wishes, reset')
}
